volumes:
  config:
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: ${STORAGE}/config
  data:
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: ${STORAGE}/data

services:
  db:
    #image: mariadb 
    image: clearlinux/mariadb
    container_name: mariadb
    hostname: mariadb
    ports:
      - 3306:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --disable-log-bin
    restart: always
    volumes:
      #- config:/etc/mysql/mariadb.conf.d
      - config:/usr/share/defaults/mariadb/my.cnf.d
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
